### ISSUE TITLE
Cannot find graph

### ISSUE THREAD

**Issue by tfjmp** [arthurscchan/ProvMark#4]
I get the following error:

```
Starting stage 4...Generating benchmark
Traceback (most recent call last):
  File "/home/vagrant/tmp/ProvMark/processGraph/findSubgraph.py", line 24, in <module>
    graph2Node, graph2Edge, graph1Props, graph2Props, map = processGraph(sys.argv[4], sys.argv[5], clingoCode)
  File "/home/vagrant/tmp/ProvMark/processGraph/clingoFunction.py", line 117, in processGraph
    file = open(graph1Path, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'general.clingo-control'
End of stage 4
```

The command is:
```
./fullAutomation.py cam /tmp ./benchmarkProgram/control ./benchmarkProgram/cmdCreat 2 ./result.clingo
```

It may be that  the `/tmp` parameter should be something different.

**Comment by jamescheney** [comment]
I think can close this now, is that OK?

**Comment by tfjmp** [comment]
Yes closing.
