### ISSUE TITLE
Permission denied /usr/lib/python3.5/subprocess.py

### ISSUE THREAD

**Issue by tfjmp** [arthurscchan/ProvMark#5]
With current master branch.

```
./fullAutomation.py cam /tmp ./benchmarkProgram/control ./benchmarkProgram/cmdCreat 2 ./result.clingo
Starting stage 1...Generating provenance from native tools
Traceback (most recent call last):
  File "/home/vagrant/workspace/ProvMark/startTool/startCamflow.py", line 78, in <module>
    subprocess.check_output(('%s/prepare %s' %(progPath, stagePath)).split())
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied
Traceback (most recent call last):
  File "/home/vagrant/workspace/ProvMark/startTool/startCamflow.py", line 78, in <module>
    subprocess.check_output(('%s/prepare %s' %(progPath, stagePath)).split())
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied
End of stage 1

```

I had to install json-merger via pip3.5 before I could get to that error.

I did as follow:
```
sudo apt install python3-setuptools
sudo easy_install3 pip
sudo pip3.5 install json_merger
```

Error may come from my python 3 install.

Command:
```
./fullAutomation.py cam /tmp ./benchmarkProgram/control ./benchmarkProgram/cmdCreat 2 ./result.clingo
```

**Comment by jamescheney** [comment]
@tfjmp does this fix the problem?
